# Generated by Django 5.1.3 on 2024-11-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvk_site', '0002_quality_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='iron',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='manganese',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='rigidity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='turbidity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='sewerage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tariffs',
            name='water',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
