# Generated by Django 5.1.3 on 2024-11-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvk_site', '0003_alter_quality_iron_alter_quality_manganese_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariffs',
            old_name='water',
            new_name='water_ch',
        ),
        migrations.AddField(
            model_name='tariffs',
            name='water_push',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
