# Generated by Django 5.1.3 on 2024-11-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvk_site', '0004_rename_water_tariffs_water_ch_tariffs_water_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='login',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribers',
            name='password',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
