# Generated by Django 5.1.3 on 2024-12-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvk_site', '0005_subscribers_login_subscribers_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribers',
            name='current_reading',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='previous_reading',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='subscribers',
            name='service_flag',
            field=models.IntegerField(choices=[(1, 'Только водоснабжение'), (2, 'Водоснабжение и канализация'), (3, 'Только канализация')], default=1),
        ),
    ]
