# Generated by Django 5.1.3 on 2024-12-21 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvk_site', '0006_subscribers_current_reading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MonthWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_work', models.IntegerField(choices=[(1, 'Вода'), (2, 'Канализация')])),
                ('year', models.IntegerField(choices=[(2024, 2024), (2025, 2025)], default=2024)),
                ('month', models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')])),
                ('completed_works', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('volume', models.FloatField(default=0.0)),
                ('summ', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeverageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2024, 2024), (2025, 2025)], default=2024)),
                ('completed_works', models.CharField(max_length=255)),
                ('january_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('january_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('february_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('february_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('march_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('march_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('first_quarter', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('april_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('april_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('may_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('may_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('june_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('june_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('second_quarter', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('july_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('july_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('august_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('august_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('september_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('september_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('third_quarter', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('october_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('october_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('november_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('november_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('december_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('december_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('fourth_quarter', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('year_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2024, 2024), (2025, 2025)], default=2024)),
                ('completed_works', models.CharField(max_length=255)),
                ('january_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('january_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('february_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('february_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('march_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('march_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('first_quarter', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('april_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('april_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('may_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('may_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('june_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('june_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('second_quarter', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('july_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('july_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('august_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('august_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('september_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('september_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('third_quarter', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('october_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('october_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('november_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('november_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('december_vol', models.FloatField(blank=True, default=0.0, null=True)),
                ('december_summ', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('fourth_quarter', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('year_total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvk_site.address'),
        ),
    ]
